/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_utils_NDKUtils */

#ifndef _Included_com_utils_NDKUtils
#define _Included_com_utils_NDKUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_utils_NDKUtils
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_utils_NDKUtils_sayHello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
